### ISSUE TITLE
Availability monitor

### ISSUE THREAD

**Issue by jkpl** [Lepovirta/lepo#32]
Set up some sort of service that monitors Lepo.IO availability, maintains statistics of the availability, and creates alerts when problems arise.

**Comment by thevangelist** [comment]
New Relic is one but probably costly

**Comment by jkpl** [comment]
A few services out there:

* [Pingdom](https://www.pingdom.com/)
* [RunScope](https://www.runscope.com/)
* [SmartBear](https://smartbear.com/product/alertsite/api-monitoring/)
* [APIMetrics](http://apimetrics.io/)
* [API Science](https://www.apiscience.com/)

**Comment by jkpl** [comment]
AWS CloudWatch could help here as well.

**Comment by jkpl** [comment]
I think I'll build something of my own, and run it in a spare DO droplet. [Prometheus](https://prometheus.io/) with [Blackbox exporter](https://github.com/prometheus/blackbox_exporter) should do the trick.

**Comment by jkpl** [comment]
Using Pingdom now.
