### ISSUE TITLE
Write styles using BEM naming convention

### ISSUE THREAD

**Issue by thevangelist** [Lepovirta/lepo#8]
http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

**Comment by jkpl** [comment]
:+1: always onboard with more maintainability

**Comment by thevangelist** [comment]
HOWTO Smacss: http://bramsmulders.com/how-i-improved-my-workflow-with-smacss-sass.html
HOWTO BEM with SCSS: http://alwaystwisted.com/articles/2014-02-27-even-easier-bem-ing-with-sass-33

**Comment by thevangelist** [comment]
SCSS + BEM:

```
<ul class="menu">
  <li class="menu__item">
    <a class="menu__link">
      <span class="menu__header"></span>
      <span class="menu__content menu__content--hidden"></span>
    </a>
  </li>
</ul>

.menu {
  &__item {}
  &__link {}
  &__header {}
  &__content {
    &--hidden {}
  }
}
```

**Comment by thevangelist** [comment]
Legacy solution.
